# Codecov settings: https://docs.codecov.com/docs/common-recipe-list
coverage:
  status:
    project:
      default:
        target: 90%
comment:
  layout: " diff, flags, files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true
  hide_project_coverage: false
ignore:
  - "custom_components/smartbox/diagnostics.py"