# Service definitions for the Smartbox integration

set_boost_params:
  name: Set boost parameters
  description: Sets temperature and duration parameters for the boost function.
  target:
    entity:
      integration: smartbox
      domain: number
  fields:
    # area_id:
    #   example: living_room
    #   selector:
    #     area:
    #       device:
    #         - integration: smartbox
    #       multiple: true
    # device_id:
    #   example: "8f4219cfa57e23f6f669c4616c2205e2"
    #   selector:
    #     device:
    #       filter:
    #         - integration: smartbox
    #       multiple: true
    # entity_id:
    #   example: sensor.living_room_temperature
    #   selector:
    #     entity:
    #       filter:
    #         - integration: smartbox
    #       multiple: true
    temperature:
      name: Temperature
      description: The target temperature to set during boost mode.
      selector:
        number:
          min: 5
          max: 30
          step: 0.5
    duration:
      name: Duration
      description: The duration of boost mode in minutes.
      selector:
        number:
          min: 60
          max: 240
          step: 60
          unit_of_measurement: "min"