# Service definitions for the Smartbox integration

set_boost_params:
  name: Set boost parameters
  description: Sets temperature and duration parameters for the boost function.
  target:
    entity:
      integration: smartbox
      domain: switch
  fields:
    entity_id:
      name: Entity
      description: The boost switch entity to configure.
      required: true
      selector:
        entity:
          integration: smartbox
          domain: switch
          filter:
            attribute:
              key: _attr_key
              value: boost
    temperature:
      name: Temperature
      description: The target temperature to set during boost mode.
      selector:
        number:
          min: 5
          max: 30
          step: 0.5
          unit_of_measurement: "°C"
    duration:
      name: Duration
      description: The duration of boost mode in minutes.
      selector:
        number:
          min: 60
          max: 240
          step: 60
          unit_of_measurement: "min" 